services:
  db:
    image: timescale/timescaledb:latest-pg16
    container_name: timescaledb
    restart: unless-stopped
    environment:
      POSTGRES_USER: rushy
      POSTGRES_PASSWORD: rushy1234
      POSTGRES_DB: readings
    ports:
      - "5432:5432"
    volumes:
      - timescaledb-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rushy -d readings"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  ml-api:
    build: ./ml-api
    container_name: ml_api
    restart: unless-stopped
    ports:
      - "8001:8000"
    networks:
      - app_network

  data-processor:
    build: ./data_processor
    container_name: data_processor
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      ml-api:
        condition: service_started
    environment:
      POSTGRES_DB: readings
      POSTGRES_USER: rushy
      POSTGRES_PASSWORD: rushy1234
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  timescaledb-data:
